# Generated by Django 2.2 on 2022-04-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
