# Generated by Django 2.2 on 2022-04-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220422_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='section',
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(help_text='Eg-one,two,three etc', max_length=100),
        ),
    ]
