# Generated by Django 3.2.8 on 2022-04-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.CharField(help_text='Eg- sct-121,sct-220,sct-560etc', max_length=100),
        ),
    ]
