# Generated by Django 2.2 on 2022-04-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220422_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.FloatField(help_text='Eg- 1,2,4,5 etc'),
        ),
    ]
