# Generated by Django 2.2 on 2022-04-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220422_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(help_text='Eg- 1.1,2.2,4.1,5.2 etc', max_length=100),
        ),
    ]
