# Generated by Django 2.2 on 2022-04-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220422_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='student',
        ),
    ]
