# Generated by Django 2.2 on 2022-04-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_unit_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='marks',
            field=models.CharField(max_length=100),
        ),
    ]
