# Generated by Django 2.2 on 2022-04-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220422_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
